
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEMODULODIVENTERAleftEXPONENTECOMMENT DIVENTERA DIVIDE EXPONENTE ID LPAREN MINUS MODULO NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term EXPONENTE factorterm : term DIVIDE factorterm : term MODULO factorterm : term DIVENTERA factorterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,10,11,12,],[4,4,4,4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,10,11,12,],[5,5,5,5,5,5,5,5,5,]),'$end':([1,2,3,4,14,15,16,17,18,19,20,21,],[0,-3,-9,-10,-1,-2,-4,-5,-6,-7,-8,-11,]),'PLUS':([1,2,3,4,13,14,15,16,17,18,19,20,21,],[6,-3,-9,-10,6,-1,-2,-4,-5,-6,-7,-8,-11,]),'MINUS':([1,2,3,4,13,14,15,16,17,18,19,20,21,],[7,-3,-9,-10,7,-1,-2,-4,-5,-6,-7,-8,-11,]),'RPAREN':([2,3,4,13,14,15,16,17,18,19,20,21,],[-3,-9,-10,21,-1,-2,-4,-5,-6,-7,-8,-11,]),'TIMES':([2,3,4,14,15,16,17,18,19,20,21,],[8,-9,-10,8,8,-4,-5,-6,-7,-8,-11,]),'EXPONENTE':([2,3,4,14,15,16,17,18,19,20,21,],[9,-9,-10,9,9,-4,-5,-6,-7,-8,-11,]),'DIVIDE':([2,3,4,14,15,16,17,18,19,20,21,],[10,-9,-10,10,10,-4,-5,-6,-7,-8,-11,]),'MODULO':([2,3,4,14,15,16,17,18,19,20,21,],[11,-9,-10,11,11,-4,-5,-6,-7,-8,-11,]),'DIVENTERA':([2,3,4,14,15,16,17,18,19,20,21,],[12,-9,-10,12,12,-4,-5,-6,-7,-8,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,13,]),'term':([0,5,6,7,],[2,2,14,15,]),'factor':([0,5,6,7,8,9,10,11,12,],[3,3,3,3,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','yacc.py',8),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','yacc.py',12),
  ('expression -> term','expression',1,'p_expression_term','yacc.py',16),
  ('term -> term TIMES factor','term',3,'p_term_times','yacc.py',20),
  ('term -> term EXPONENTE factor','term',3,'p_term_exponente','yacc.py',24),
  ('term -> term DIVIDE factor','term',3,'p_term_div','yacc.py',28),
  ('term -> term MODULO factor','term',3,'p_term_mod','yacc.py',32),
  ('term -> term DIVENTERA factor','term',3,'p_term_divent','yacc.py',36),
  ('term -> factor','term',1,'p_term_factor','yacc.py',40),
  ('factor -> NUMBER','factor',1,'p_factor_num','yacc.py',44),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','yacc.py',48),
]
